# Generated by Django 4.1.2 on 2022-10-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_commentmessage_user_foto_delete_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmessage',
            options={'ordering': ('-date_updated',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterModelOptions(
            name='commentmessage',
            options={'ordering': ('date_added',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-last_login',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='boardmessage',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='boardmessage',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='commentmessage',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='commentmessage',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='commentmessage',
            name='text',
            field=models.TextField(verbose_name='Ваш комментарий'),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='users_foto', verbose_name='Фото'),
        ),
    ]
